# -*- coding: utf-8 -*-
"""NASA data

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8FHsTUiB8unE5AZfjDMTwyKDVwbZXmw

Get the media urls from NASA API
"""

import json
import requests

def get_data(api):
  response = requests.get(f"{api}")
  if response.status_code == 200:
    print("sucessfully fetched the data")
    return response.json()
  else:
    print(f"There's a {response.status_code} error with your request")


# Get Responses
data = get_data('https://images-api.nasa.gov/search?q=%27%27')

# Data Extract
items = data['collection']['items']
mediaUrl = []
for item in items:
  mediaUrl.append(item['links'][0]['href'])

for url in mediaUrl:
  # Print the index:
  print(mediaUrl.index(url))
  print(url)
"""
from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/NASA_media/'  #change dir to project folder



import os
import urllib.request
from tqdm import tqdm


for url in tqdm(mediaUrl):
  try:
    #print(str(url))
    !wget -q "$url" -P "/content/gdrive/My Drive/NASA_Media" # type: ignore
    #urllib.request.urlretrieve(url)
  except Exception as e:
    print(e)
    pass
"""